### ISSUE TITLE
Error when used in base_url

### ISSUE THREAD

**Issue by bagaskarala** [agungjk/phpdotenv-for-codeigniter#6]
if i set this `$config['base_url'] = getenv('CONFIG_BASE_URL');`, then whe echoing site_url would return `[::1]`

**Comment by ConnorHowell** [comment]
This may be a little late, but for anyone coming across this:

1. For starters use: https://github.com/vlucas/phpdotenv instead of this as this library is now 3 years out of date and is the same but out of date and copied into the system directory.

2. Make sure you've setup composer autoload in the config.

3. Create a 'pre_system' hook to load the .env file:
```
$hook['pre_system'] = function () {
    $dotenv = Dotenv\Dotenv::createImmutable(FCPATH);
    $dotenv->load();
};
```

4. Then to answer OPs question, leave the base_url as a blank string; then in another config file (I used routes.php) add the following:
`$this->config->set_item('base_url', $_ENV['YOUR_URL_VAR']);`

This way there is no need to modify any codeigniter system files...

**Comment by shqawe1** [comment]
> This may be a little late, but for anyone coming across this:
> 
>     1. For starters use: https://github.com/vlucas/phpdotenv instead of this as this library is now 3 years out of date and is the same but out of date and copied into the system directory.
> 
>     2. Make sure you've setup composer autoload in the config.
> 
>     3. Create a 'pre_system' hook to load the .env file:
> 
> 
> ```
> $hook['pre_system'] = function () {
>     $dotenv = Dotenv\Dotenv::createImmutable(FCPATH);
>     $dotenv->load();
> };
> ```
> 
>     1. Then to answer OPs question, leave the base_url as a blank string; then in another config file (I used routes.php) add the following:
>        `$this->config->set_item('base_url', $_ENV['YOUR_URL_VAR']);`
> 
> 
> This way there is no need to modify any codeigniter system files...

Thanks @ConnorHowell1 i use this package as you mentioned vlucas/phpdotenv and it's work fine with after i add hook thanks again.
